### ISSUE TITLE
noise: Add 3D Perlin Noise to noise module

### ISSUE THREAD

**Issue by ulises-jeremias** [vlang/vsl#163]
### Describe the feature

Add a 3D perlin noise implementation to `vsl.noise`

### Use Case

Perlin noise is a procedural texture primitive, a type of gradient noise used by visual effects artists to increase the appearance of realism in computer graphics. The function has a pseudo-random appearance, yet all of its visual details are the same size.

We already have a 2D implementation of the Perlin Noise, so the scope of this is to have a new 3D implementation as well

### Proposed Solution

- [x] #164
- [ ] Implement 3D Perlin Noise

### Other Information

-

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### Version used

-

### Environment details (OS name and version, etc.)

-

**Comment by prithvidasgupta** [comment]
@ulises-jeremias I was working on the 3d noise generation today (just trying out VLang). I think there is a bug on https://github.com/vlang/vsl/blob/02221fde8ed188bdc7e25f9b8df4aea961837edc/noise/perlin.v#L33 

shouldn't it be ` sy := y - f32(y1)` ? Or is my undestanding incorrect?

**Comment by ulises-jeremias** [comment]
just in case I'll include @boonsboos on this conversation because he was the creator of that module 😊 in any case, I'll take a look later just to confirm!

**Comment by prithvidasgupta** [comment]
@ulises-jeremias should i just port Perlin's original implementation to vlang/vsl? https://mrl.cs.nyu.edu/~perlin/noise/

**Comment by PottierLoic** [comment]
Hello i just compared a basic noise function (random value everywhere, no perlin or other stuffs) and the 2d perlin noise from vsl.

![noise_basic](https://github.com/vlang/vsl/assets/84566637/b9431d60-307d-484b-9d1f-d928dd3cd30b)

and

![noise_perlin](https://github.com/vlang/vsl/assets/84566637/5a3f3c71-8a12-48e5-a376-4de2cc61861f)

Perlin noise should be way smoother so I made another implementation based on this https://adrianb.io/2014/08/09/perlinnoise.html and it looks like this :

![new_perlin](https://github.com/vlang/vsl/assets/84566637/56bc70cb-926f-474b-bc08-c139e2bbc3fd)
(The little glitch on the bottom is only caused by the screenshot)

Can I try to submit a PR for 2d and 3d perlin ?

**Comment by ulises-jeremias** [comment]
@PottierLoic sure! Go for it!
