### ISSUE TITLE
vsl.plot not working in windows

### ISSUE THREAD

**Issue by holder66** [vlang/vsl#78]
holder66.hamnn CI workflow using windows-latest:
https://github.com/holder66/hamnn/runs/5589144170?check_suite_focus=true

**VSL version:** 
**OS:** 

**What did you do?**

**What did you expect to see?**

 
**What did you see instead?**

**Comment by ulises-jeremias** [comment]
We are using python and bash behind the scenes. We need to adapt it to use something else and but still python for windows

**Comment by JalonSolov** [comment]
We just need a pure V version...  :-)

**Comment by ulises-jeremias** [comment]
@JalonSolov not for this ticket and probably not for the next 2 months 😅

**Comment by ulises-jeremias** [comment]
some context here. Seems that is it working on windows for users that have bash installed. So we need to figure out a way to know if bash is installed. Otherwise we need to provide another way of running the scripts that it provides

One way is to migrate all the `.sh` files in the `plot/` dir to `.vsh` instead. That way VSL plot will be using V for motly everything and just using python to run the plot server, which is a better way of doing it
